import type { Organization } from "@/components/miljoer-explorer";

// Kilde til sannhet for alle innovasjonsmiljøer/studentorganisasjoner som vises
// som kort på /miljoer. Antall (organizations.length) brukes også til den live
// tellingen på forsiden, slik at statistikken alltid matcher antall kort.
export const organizations: Organization[] = [
  {
    accent: "yellow",
    href: "https://www.ascendntnu.no",
    logo: "/assets/logos/ascend.webp",
    logoAlt: "Ascend NTNU",
    logoSize: "tall",
    photo: "/assets/heroes/ascend.webp",
    photoAlt: "Ascend NTNU-teamet med dronen på konkurranse",
    category: "TO · Droner",
    name: "Ascend NTNU",
    description:
      "Konkurrerer i internasjonale drone-konkurranser med autonome systemer.",
  },
  {
    accent: "red",
    href: "https://www.boosthenne.no",
    logo: "/assets/logos/boosthenne.webp",
    logoAlt: "Boost Henne",
    photo: "/assets/heroes/boosthenne.webp",
    photoAlt: "Boost Henne-arrangement",
    photoPosition: "center top",
    category: "Arrangør · Kvinnenettverk",
    name: "Boost Henne",
    description:
      "Kvinnenettverk for studenter som vil inn i entreprenørskap. Rollemodeller, mentorer og events.",
  },
  {
    accent: "teal",
    href: "https://www.brainntnu.no",
    logo: "/assets/partners/brain-ntnu.webp",
    logoAlt: "BRAIN NTNU",
    photo: "/assets/heroes/brain.webp",
    photoAlt: "BRAIN NTNU-teamet",
    category: "AI · Teknologi",
    name: "BRAIN NTNU",
    description:
      "Arrangerer hackathons, foredrag og møteplasser innen kunstig intelligens.",
  },
  {
    accent: "yellow",
    href: "https://www.cogito-ntnu.no/",
    media: "dark",
    logo: "/assets/logos/cogito-white.webp",
    logoAlt: "Cogito",
    photo: "/assets/heroes/cogito.webp",
    photoAlt: "Cogito-teamet",
    category: "AI · Prosjekter",
    name: "Cogito",
    description:
      "Utvikler AI-løsninger og bygger erfaring gjennom semesterprosjekter.",
  },
  {
    accent: "teal",
    href: "https://www.designhjelpen.no",
    logo: "/assets/logos/designhjelpen.webp",
    logoAlt: "Designhjelpen",
    logoSize: "big",
    photo: "/assets/heroes/designhjelpen.avif",
    photoAlt: "Designhjelpen-teamet",
    category: "Konsulent · Design",
    name: "Designhjelpen",
    description:
      "Designstudenter hjelper andre orgs og oppstarter med visuell identitet, web og UX.",
  },
  {
    accent: "red",
    href: "https://www.instagram.com/drivntnu",
    logo: "/assets/logos/driv.webp",
    logoAlt: "DRIV NTNU",
    photo: "/assets/heroes/driv.webp",
    photoAlt: "DRIV NTNU-aktivitet",
    category: "Helse · Innovasjon",
    name: "DRIV NTNU",
    description:
      "Kobler studenter med reelle helseutfordringer og et tverrfaglig innovasjonsmiljø.",
  },
  {
    accent: "red",
    href: "https://www.entreprenorskolen.no/",
    logo: "/assets/logos/entreprenorskolen.webp",
    logoAlt: "NTNU School of Entrepreneurship",
    photo: "/assets/heroes/entreprenorskolen.webp",
    photoAlt: "Stand for NTNU School of Entrepreneurship på Fram",
    category: "Master",
    name: "Entreprenørskolen",
    description:
      "NTNUs master i entreprenørskap (NSE). To år der du bygger et reelt selskap som eksamen.",
  },
  {
    accent: "teal",
    href: "https://fuelfighter.no",
    logo: "/assets/to/fuelfighter.webp",
    logoAlt: "Fuel Fighter",
    photo: "/assets/heroes/fuelfighter.webp",
    photoAlt: "Fuel Fighter-teamet med kjøretøy",
    category: "TO · Bil",
    name: "Fuel Fighter",
    description:
      "Bygger ultra-energieffektive kjøretøy til Shell Eco-marathon.",
  },
  {
    accent: "yellow",
    href: "https://www.gridvillentnu.com/",
    media: "dark",
    logo: "/assets/logos/gridville-white2.webp",
    logoAlt: "Gridville",
    photo: "/assets/heroes/gridville.webp",
    photoAlt: "Gridville-teamet",
    category: "TO · Energi",
    name: "Gridville",
    description:
      "Studentprosjekter på fornybar energi, mikro­nett og smart strømforsyning.",
  },
  {
    accent: "blue",
    href: "https://www.grunderbrakka.no",
    logo: "/assets/logos/grunderbrakka.webp",
    logoAlt: "Gründerbrakka",
    photo: "/assets/heroes/grunderbrakka.webp",
    photoAlt: "Gründerbrakka lokalene",
    category: "Coworking",
    name: "Gründerbrakka",
    description:
      "Coworking-plass for ambisiøse oppstarter. Faste kontorplasser og investor­nettverk.",
  },
  {
    accent: "teal",
    href: "https://www.hackerspace-ntnu.no",
    media: "dark",
    logo: "/assets/logos/hackerspace.webp",
    logoAlt: "Hackerspace NTNU",
    logoSize: "big",
    photo: "/assets/heroes/hackerspace.webp",
    photoAlt: "Hackerspace NTNU-lokalet",
    category: "Makerspace",
    name: "Hackerspace NTNU",
    description:
      "Studentdrevet makerspace — lodding, 3D-print, software-prosjekter og workshops.",
  },
  {
    accent: "yellow",
    href: "https://iug.no/om-oss/lokalavdelinger/iug-ntnu",
    logo: "/assets/logos/iug.webp",
    logoAlt: "Ingeniører uten grenser",
    photo: "/assets/heroes/iug.webp",
    photoAlt: "Ingeniører uten grenser-prosjekt",
    category: "Humanitær",
    name: "Ingeniører uten grenser",
    description:
      "Teknisk bistand og prosjekter i utviklingsland — rent vann, skoler, energi.",
  },
  {
    accent: "red",
    href: "https://www.instagram.com/innovationtnu/",
    media: "dark-navy",
    logo: "/assets/logos/innovatio.webp",
    logoAlt: "Innovatio",
    logoSize: "big-tall",
    photo: "/assets/heroes/innovatio.webp",
    photoAlt: "Innovatio-teamet",
    photoPosition: "center 22%",
    category: "Linjeforening",
    name: "Innovatio",
    description:
      "Linjeforeningen for masterprogrammet i Innovasjon og bærekraftig samfunnsutvikling ved NTNU i Trondheim.",
  },
  {
    accent: "red",
    href: "https://www.jetntnu.no/",
    media: "dark",
    logo: "/assets/logos/jet-white.svg",
    logoAlt: "Jet NTNU",
    logoSize: "big",
    photo: "/assets/heroes/jet.webp",
    photoAlt: "Jet NTNU turbojetmotor",
    spin: true,
    category: "TO · Jetmotor",
    name: "Jet NTNU",
    description:
      "Norges første studentdrevne jetmotororganisasjon. Designer, produserer og tester sin egen turbojetmotor.",
  },
  {
    accent: "teal",
    href: "https://makentnu.no/",
    logo: "/assets/logos/make.webp",
    logoAlt: "Make NTNU",
    photo: "/assets/heroes/make.webp",
    photoAlt: "Make NTNU 3D-printere",
    photoPosition: "center 35%",
    category: "Makerspace",
    name: "Make NTNU",
    description:
      "Gir studenter tilgang til verktøy, utstyr og kompetanse for å bygge egne prosjekter.",
  },
  {
    accent: "blue",
    href: "https://marinorntnu.no/",
    logo: "/assets/logos/marinor.png",
    logoAlt: "Marinor NTNU",
    logoSize: "xl",
    photo: "/assets/heroes/marinor.webp",
    photoAlt: "Marinor NTNU-laget med sitt autonome fartøy",
    photoPosition: "center 62%",
    category: "TO · Autonomi",
    name: "Marinor NTNU",
    description:
      "Bygger og tester autonome maritime systemer, og bruker forskning til å løse reelle utfordringer til havs.",
  },
  {
    accent: "blue",
    href: "https://www.njordntnu.no/",
    logo: "/assets/to/njord.webp",
    logoAlt: "Njord",
    logoSize: "big",
    photo: "/assets/heroes/njord.webp",
    photoAlt: "Njord autonome fartøy på vannet",
    category: "TO · Hav",
    name: "Njord",
    description:
      "Arrangerer en internasjonal konkurranse for selvstyrte skip, og bygger sine egne autonome fartøy.",
  },
  {
    accent: "red",
    href: "https://www.nordlysntnu.no/",
    logo: "/assets/logos/nordlys.webp",
    logoAlt: "Nordlys Solar Racing",
    logoSize: "big",
    photo: "/assets/heroes/nordlys.webp",
    photoAlt: "Nordlys-teamet med solbil",
    category: "TO · Solbil",
    name: "Nordlys",
    description:
      "Bygger og konkurrerer med soldrevne racerbiler i internasjonale solbilløp.",
  },
  {
    accent: "blue",
    href: "https://www.norstec.no/",
    logo: "/assets/logos/norstec.webp",
    logoAlt: "NORSTEC",
    photo: "/assets/heroes/norstec-ledere.webp",
    photoAlt: "NORSTEC-lederne foran anlegget",
    photoPosition: "center 72%",
    category: "Rom · Nettverk",
    name: "NORSTEC",
    description:
      "Forener studentorganisasjoner innen romteknologi og skaper nye muligheter gjennom samarbeid.",
  },
  {
    accent: "blue",
    href: "https://norstec.no/summit",
    media: "dark",
    logo: "/assets/logos/norstec-summit-white.webp",
    logoAlt: "NORSTEC Summit",
    photo: "/assets/heroes/norstec.webp",
    photoAlt: "NORSTEC romkonferanse",
    category: "Rom · Konferanse",
    name: "NORSTEC Summit",
    description:
      "Samler studenter, industri og myndigheter til Norges største studentdrevne romkonferanse.",
  },
  {
    accent: "blue",
    href: "https://www.orbitntnu.com/",
    media: "dark",
    logo: "/assets/logos/orbit.webp",
    logoAlt: "Orbit NTNU",
    photo: "/assets/heroes/orbit.webp",
    photoAlt: "Orbit-satellitt i bane",
    category: "TO · Satellitter",
    name: "Orbit NTNU",
    description:
      "Bygger CubeSat-satellitter. Første student-satellitt i bane fra NTNU.",
  },
  {
    accent: "blue",
    href: "https://www.propulse.no/",
    logo: "/assets/logos/propulse.webp",
    logoAlt: "Propulse NTNU",
    logoSize: "big",
    photo: "/assets/heroes/propulse.webp",
    photoAlt: "Propulse-rakett avduking",
    category: "TO · Raketter",
    name: "Propulse NTNU",
    description:
      "Designer, bygger og skyter opp væskedrevne forskningsraketter.",
  },
  {
    accent: "red",
    href: "https://reluntnu.no/",
    media: "dark",
    logo: "/assets/logos/relu.webp",
    logoAlt: "Relu",
    photo: "/assets/heroes/relu.webp",
    photoAlt: "Relu-presentasjon",
    category: "AI · Industri",
    name: "Relu",
    description: "Utvikler AI-løsninger i samarbeid med næringslivet.",
  },
  {
    accent: "teal",
    href: "https://www.revolve.no/",
    logo: "/assets/logos/revolve.webp",
    logoAlt: "Revolve NTNU",
    logoSize: "tall",
    photo: "/assets/heroes/revolve.webp",
    photoAlt: "Revolve-bil på banen",
    category: "TO · Motorsport",
    name: "Revolve NTNU",
    description:
      "Formula Student — designer og bygger en ny elektrisk racerbil hvert år.",
  },
  {
    accent: "teal",
    href: "https://www.instagram.com/solanlinjeforening",
    logo: "/assets/logos/solan-new.webp",
    logoAlt: "Solan Linjeforening",
    logoSize: "tall",
    photo: "/assets/heroes/solan.webp",
    photoAlt: "Solan Linjeforening-teamet",
    category: "Linjeforening",
    name: "Solan",
    description: "Linjeforeningen for Entreprenørskolen ved NTNU i Trondheim.",
  },
  {
    accent: "blue",
    href: "https://sparkntnu.no/",
    logo: "/assets/spark-logo.webp",
    logoAlt: "Spark NTNU",
    photo: "/assets/heroes/spark-org.webp",
    photoAlt: "Spark NTNU-arrangement",
    photoPosition: "center top",
    category: "Veiledning",
    name: "Spark* NTNU",
    description:
      "Gratis veiledningstjeneste for studenter med en forretningsidé — mentorer, workshops og et program fra post-it til pilot.",
  },
  {
    accent: "yellow",
    href: "https://www.startntnu.no/",
    logo: "/assets/partners/start-ntnu.webp",
    logoAlt: "Start NTNU",
    photo: "/assets/heroes/start.webp",
    photoAlt: "Start IT-arrangement",
    category: "Arrangør · Entreprenørskap",
    name: "Start NTNU",
    description:
      "Norges største studentorganisasjon for entreprenørskap. Startup Weekend, pitch-kvelder og karriere­events.",
  },
  {
    accent: "blue",
    href: "https://www.instagram.com/studiobeta/",
    logo: "/assets/logos/studiobeta.webp",
    logoAlt: "Studio Beta",
    photo: "/assets/heroes/studiobeta.webp",
    photoAlt: "Studio Beta-byggeprosjekt",
    category: "Arkitektur",
    name: "Studio Beta",
    description:
      "Studentdrevet arkitektur- og designstudio. Byggeprosjekter i full skala og prototyper.",
  },
  {
    accent: "yellow",
    href: "https://www.stottehjulet.no/",
    logo: "/assets/logos/stottehjulet.webp",
    logoAlt: "Støttehjulet",
    logoSize: "big-tall",
    photo: "/assets/heroes/stottehjulet.avif",
    photoAlt: "Støttehjulet-teamet",
    category: "Konsulent · Organisasjon",
    name: "Støttehjulet",
    description:
      "Hjelper organisasjoner med ledelse, samarbeid og organisasjonsutvikling.",
  },
  {
    accent: "red",
    href: "https://www.vortexntnu.no",
    media: "deeper",
    logo: "/assets/to/ascend.webp",
    logoAlt: "Vortex NTNU",
    logoSize: "big",
    photo: "/assets/heroes/vortex.webp",
    photoAlt: "Vortex ORCA undervannsfarkost",
    category: "TO · Undervann",
    name: "Vortex NTNU",
    description:
      "Bygger autonome undervannsfarkoster (ROV/AUV) til internasjonale konkurranser.",
  },
  {
    accent: "yellow",
    href: "https://www.instagram.com/wic_ntnu/",
    media: "dark",
    logo: "/assets/logos/wic.webp",
    logoAlt: "WIC — Women’s Investment Club",
    photo: "/assets/heroes/wic.webp",
    photoAlt: "WIC-arrangement",
    photoPosition: "center 35%",
    category: "Finans · Kvinnenettverk",
    name: "WIC",
    description:
      "Women’s Investment Club skaper møteplasser for kvinner med interesse for finans, investering og kapitalmarkeder.",
  },
  {
    accent: "red",
    href: "https://womeninaintnu.no/",
    logo: "/assets/logos/womeninai.webp",
    logoAlt: "Women in AI NTNU",
    logoSize: "big",
    photo: "/assets/heroes/womeninai.webp",
    photoAlt: "Women in AI NTNU-teamet på trappa",
    photoPosition: "center 20%",
    category: "AI · Kvinnenettverk",
    name: "Women in AI",
    description:
      "NTNUs første kvinnelige studentorganisasjon innen AI. Bygger ekte AI-kompetanse gjennom prosjekter for reelle bedrifter.",
  },
];
