import type { Organization } from "@/components/miljoer-explorer";

// Kilde til sannhet for alle innovasjonsmiljøer/studentorganisasjoner som vises
// som kort på /miljoer. Antall (organizations.length) brukes også til den live
// tellingen på forsiden, slik at statistikken alltid matcher antall kort.
//
// `category`/`description` er den norske teksten som vises på kortene.
// `categoryEn`/`descriptionEn` er den engelske motparten (vises på /en/communities).
export const organizations: Organization[] = [
  {
    accent: "yellow",
    href: "https://www.ascendntnu.no",
    logo: "/assets/logos/ascend.webp",
    logoAlt: "Ascend NTNU",
    logoSize: "tall",
    photo: "/assets/heroes/ascend.webp",
    photoAlt: "Ascend NTNU-teamet med dronen på konkurranse",
    category: "Luft · Droner",
    categoryEn: "Air · Drones",
    name: "Ascend NTNU",
    description:
      "Konkurrerer i internasjonale drone-konkurranser med autonome systemer.",
    descriptionEn:
      "Competes in international drone competitions with autonomous systems.",
  },
  {
    accent: "red",
    href: "https://www.boosthenne.no",
    logo: "/assets/logos/boosthenne.webp",
    logoAlt: "Boost Henne",
    photo: "/assets/heroes/boosthenne.webp",
    photoAlt: "Boost Henne-arrangement",
    photoPosition: "center top",
    category: "Kvinnenettverk",
    categoryEn: "Women's network",
    name: "Boost Henne",
    description:
      "Kvinnenettverk for studenter som vil inn i entreprenørskap. Rollemodeller, mentorer og events.",
    descriptionEn:
      "A women's network for students who want to get into entrepreneurship. Role models, mentors and events.",
  },
  {
    accent: "teal",
    href: "https://www.brainntnu.no",
    logo: "/assets/partners/brain-ntnu.webp",
    logoAlt: "BRAIN NTNU",
    photo: "/assets/heroes/brain.webp",
    photoAlt: "BRAIN NTNU-teamet",
    category: "AI · Teknologi",
    categoryEn: "AI · Technology",
    name: "BRAIN NTNU",
    description:
      "Arrangerer hackathons, foredrag og møteplasser innen kunstig intelligens.",
    descriptionEn:
      "Hosts hackathons, talks and meetups around artificial intelligence.",
  },
  {
    accent: "yellow",
    href: "https://www.cogito-ntnu.no/",
    media: "dark",
    logo: "/assets/logos/cogito-white.webp",
    logoAlt: "Cogito",
    photo: "/assets/heroes/cogito.webp",
    photoAlt: "Cogito-teamet",
    category: "AI · Prosjekter",
    categoryEn: "AI · Projects",
    name: "Cogito",
    description:
      "Utvikler AI-løsninger og bygger erfaring gjennom semesterprosjekter.",
    descriptionEn:
      "Builds AI solutions and hands-on experience through semester projects.",
  },
  {
    accent: "teal",
    href: "https://www.designhjelpen.no",
    logo: "/assets/logos/designhjelpen.webp",
    logoAlt: "Designhjelpen",
    logoSize: "big",
    photo: "/assets/heroes/designhjelpen.avif",
    photoAlt: "Designhjelpen-teamet",
    category: "Konsulent · Design",
    categoryEn: "Consulting · Design",
    name: "Designhjelpen",
    description:
      "Designstudenter hjelper andre orgs og oppstarter med visuell identitet, web og UX.",
    descriptionEn:
      "Design students help other orgs and startups with visual identity, web and UX.",
  },
  {
    accent: "red",
    href: "https://www.instagram.com/drivntnu",
    logo: "/assets/logos/driv.webp",
    logoAlt: "DRIV NTNU",
    photo: "/assets/heroes/driv.webp",
    photoAlt: "DRIV NTNU-aktivitet",
    category: "Helse · Innovasjon",
    categoryEn: "Health · Innovation",
    name: "DRIV NTNU",
    description:
      "Kobler studenter med reelle helseutfordringer og et tverrfaglig innovasjonsmiljø.",
    descriptionEn:
      "Connects students with real health challenges and an interdisciplinary innovation community.",
  },
  {
    accent: "red",
    href: "https://www.entreprenorskolen.no/",
    logo: "/assets/logos/entreprenorskolen.webp",
    logoAlt: "NTNU School of Entrepreneurship",
    photo: "/assets/heroes/entreprenorskolen.webp",
    photoAlt: "Stand for NTNU School of Entrepreneurship på Fram",
    category: "Master",
    categoryEn: "Master's",
    name: "Entreprenørskolen",
    description:
      "NTNUs master i entreprenørskap (NSE). To år der du bygger et reelt selskap som eksamen.",
    descriptionEn:
      "NTNU's master's in entrepreneurship (NSE). Two years spent building a real company as your exam.",
  },
  {
    accent: "teal",
    href: "https://fuelfighter.no",
    logo: "/assets/to/fuelfighter.webp",
    logoAlt: "Fuel Fighter",
    photo: "/assets/heroes/fuelfighter.webp",
    photoAlt: "Fuel Fighter-teamet med kjøretøy",
    category: "Energi · Bil",
    categoryEn: "Energy · Cars",
    name: "Fuel Fighter",
    description:
      "Bygger ultra-energieffektive kjøretøy til Shell Eco-marathon.",
    descriptionEn:
      "Builds ultra energy-efficient vehicles for the Shell Eco-marathon.",
  },
  {
    accent: "yellow",
    href: "https://www.gridvillentnu.com/",
    media: "dark",
    logo: "/assets/logos/gridville-white2.webp",
    logoAlt: "Gridville",
    photo: "/assets/heroes/gridville.webp",
    photoAlt: "Gridville-teamet",
    category: "Energi · Nett",
    categoryEn: "Energy · Grid",
    name: "Gridville",
    description:
      "Studentprosjekter på fornybar energi, mikro­nett og smart strømforsyning.",
    descriptionEn:
      "Student projects in renewable energy, microgrids and smart power supply.",
  },
  {
    accent: "blue",
    href: "https://www.grunderbrakka.no",
    logo: "/assets/logos/grunderbrakka.webp",
    logoAlt: "Gründerbrakka",
    photo: "/assets/heroes/grunderbrakka.webp",
    photoAlt: "Gründerbrakka lokalene",
    category: "Coworking",
    categoryEn: "Coworking",
    name: "Gründerbrakka",
    description:
      "Coworking-plass for ambisiøse oppstarter. Faste kontorplasser og investor­nettverk.",
    descriptionEn:
      "A coworking space for ambitious startups. Dedicated desks and an investor network.",
  },
  {
    accent: "teal",
    href: "https://www.hackerspace-ntnu.no",
    media: "dark",
    logo: "/assets/logos/hackerspace.webp",
    logoAlt: "Hackerspace NTNU",
    logoSize: "big",
    photo: "/assets/heroes/hackerspace.webp",
    photoAlt: "Hackerspace NTNU-lokalet",
    category: "Makerspace",
    categoryEn: "Makerspace",
    name: "Hackerspace NTNU",
    description:
      "Studentdrevet makerspace — lodding, 3D-print, software-prosjekter og workshops.",
    descriptionEn:
      "A student-run makerspace — soldering, 3D printing, software projects and workshops.",
  },
  {
    accent: "yellow",
    href: "https://iug.no/om-oss/lokalavdelinger/iug-ntnu",
    logo: "/assets/logos/iug.webp",
    logoAlt: "Ingeniører uten grenser",
    photo: "/assets/heroes/iug.webp",
    photoAlt: "Ingeniører uten grenser-prosjekt",
    category: "Humanitær",
    categoryEn: "Humanitarian",
    name: "Ingeniører uten grenser",
    description:
      "Teknisk bistand og prosjekter i utviklingsland — rent vann, skoler, energi.",
    descriptionEn:
      "Technical aid and projects in developing countries — clean water, schools, energy.",
  },
  {
    accent: "red",
    href: "https://www.instagram.com/innovationtnu/",
    media: "dark-navy",
    logo: "/assets/logos/innovatio.webp",
    logoAlt: "Innovatio",
    logoSize: "big-tall",
    photo: "/assets/heroes/innovatio.webp",
    photoAlt: "Innovatio-teamet",
    photoPosition: "center 22%",
    category: "Linjeforening",
    categoryEn: "Student society",
    name: "Innovatio",
    description:
      "Linjeforeningen for masterprogrammet i Innovasjon og bærekraftig samfunnsutvikling ved NTNU i Trondheim.",
    descriptionEn:
      "The student society for the master's programme in Innovation and Sustainable Development at NTNU in Trondheim.",
  },
  {
    accent: "red",
    href: "https://www.jetntnu.no/",
    media: "dark",
    logo: "/assets/logos/jet-white.svg",
    logoAlt: "Jet NTNU",
    logoSize: "big",
    photo: "/assets/heroes/jet.webp",
    photoAlt: "Jet NTNU turbojetmotor",
    spin: true,
    category: "Luft · Jetmotor",
    categoryEn: "Air · Jet engine",
    name: "Jet NTNU",
    description:
      "Norges første studentdrevne jetmotororganisasjon. Designer, produserer og tester sin egen turbojetmotor.",
    descriptionEn:
      "Norway's first student-run jet engine organisation. Designs, builds and tests its own turbojet engine.",
  },
  {
    accent: "teal",
    href: "https://makentnu.no/",
    logo: "/assets/logos/make.webp",
    logoAlt: "Make NTNU",
    photo: "/assets/heroes/make.webp",
    photoAlt: "Make NTNU 3D-printere",
    photoPosition: "center 35%",
    category: "Makerspace",
    categoryEn: "Makerspace",
    name: "Make NTNU",
    description:
      "Gir studenter tilgang til verktøy, utstyr og kompetanse for å bygge egne prosjekter.",
    descriptionEn:
      "Gives students access to the tools, equipment and know-how to build their own projects.",
  },
  {
    accent: "blue",
    href: "https://marinorntnu.no/",
    logo: "/assets/logos/marinor.png",
    logoAlt: "Marinor NTNU",
    logoSize: "xl",
    photo: "/assets/heroes/marinor.webp",
    photoAlt: "Marinor NTNU-laget med sitt autonome fartøy",
    photoPosition: "center 62%",
    category: "Hav · Autonomi",
    categoryEn: "Ocean · Autonomy",
    name: "Marinor NTNU",
    description:
      "Bygger og tester autonome maritime systemer, og bruker forskning til å løse reelle utfordringer til havs.",
    descriptionEn:
      "Builds and tests autonomous maritime systems, using research to solve real challenges at sea.",
  },
  {
    accent: "blue",
    href: "https://www.njordntnu.no/",
    logo: "/assets/to/njord.webp",
    logoAlt: "Njord",
    logoSize: "big",
    photo: "/assets/heroes/njord.webp",
    photoAlt: "Njord autonome fartøy på vannet",
    category: "Hav · Autonomi",
    categoryEn: "Ocean · Autonomy",
    name: "Njord",
    description:
      "Arrangerer en internasjonal konkurranse for selvstyrte skip, og bygger sine egne autonome fartøy.",
    descriptionEn:
      "Runs an international competition for autonomous ships, and builds its own self-navigating vessels.",
  },
  {
    accent: "red",
    href: "https://www.nordlysntnu.no/",
    logo: "/assets/logos/nordlys.webp",
    logoAlt: "Nordlys Solar Racing",
    logoSize: "big",
    photo: "/assets/heroes/nordlys.webp",
    photoAlt: "Nordlys-teamet med solbil",
    category: "Energi · Bil",
    categoryEn: "Energy · Cars",
    name: "Nordlys",
    description:
      "Bygger og konkurrerer med soldrevne racerbiler i internasjonale solbilløp.",
    descriptionEn:
      "Builds and races solar-powered cars in international solar car challenges.",
  },
  {
    accent: "blue",
    href: "https://www.norstec.no/",
    logo: "/assets/logos/norstec.webp",
    logoAlt: "NORSTEC",
    photo: "/assets/heroes/norstec-ledere.webp",
    photoAlt: "NORSTEC-lederne foran anlegget",
    photoPosition: "center 72%",
    category: "Rom · Nettverk",
    categoryEn: "Space · Network",
    name: "NORSTEC",
    description:
      "Forener studentorganisasjoner innen romteknologi og skaper nye muligheter gjennom samarbeid.",
    descriptionEn:
      "Unites student organisations in space technology and creates new opportunities through collaboration.",
  },
  {
    accent: "blue",
    href: "https://norstec.no/summit",
    media: "dark",
    logo: "/assets/logos/norstec-summit-white.webp",
    logoAlt: "NORSTEC Summit",
    photo: "/assets/heroes/norstec.webp",
    photoAlt: "NORSTEC romkonferanse",
    category: "Rom · Konferanse",
    categoryEn: "Space · Conference",
    name: "NORSTEC Summit",
    description:
      "Samler studenter, industri og myndigheter til Norges største studentdrevne romkonferanse.",
    descriptionEn:
      "Brings students, industry and government together at Norway's largest student-run space conference.",
  },
  {
    accent: "blue",
    href: "https://ntnuseismic.no/",
    media: "dark",
    logo: "/assets/logos/seismic.webp",
    logoAlt: "NTNU Seismic",
    logoSize: "big",
    photo: "/assets/heroes/seismic.webp",
    photoAlt: "NTNU Seismic-medlem som bygger en jordskjelvsikker tårnmodell i balsatre",
    category: "Byggteknikk · Konstruksjon",
    categoryEn: "Structural · Engineering",
    name: "NTNU Seismic",
    description:
      "Konkurrerer i den internasjonale Seismic Design Competition — designer og bygger jordskjelvsikre tårnmodeller.",
    descriptionEn:
      "Competes in the international Seismic Design Competition — designing and building earthquake-proof tower models.",
  },
  {
    accent: "blue",
    href: "https://www.orbitntnu.com/",
    media: "dark",
    logo: "/assets/logos/orbit.webp",
    logoAlt: "Orbit NTNU",
    photo: "/assets/heroes/orbit.webp",
    photoAlt: "Orbit-satellitt i bane",
    category: "Rom · Satellitter",
    categoryEn: "Space · Satellites",
    name: "Orbit NTNU",
    description:
      "Bygger CubeSat-satellitter. Første student-satellitt i bane fra NTNU.",
    descriptionEn:
      "Builds CubeSat satellites. The first student satellite in orbit from NTNU.",
  },
  {
    accent: "blue",
    href: "https://www.propulse.no/",
    logo: "/assets/logos/propulse.webp",
    logoAlt: "Propulse NTNU",
    logoSize: "big",
    photo: "/assets/heroes/propulse.webp",
    photoAlt: "Propulse-rakett avduking",
    category: "Rom · Raketter",
    categoryEn: "Space · Rockets",
    name: "Propulse NTNU",
    description:
      "Designer, bygger og skyter opp væskedrevne forskningsraketter.",
    descriptionEn:
      "Designs, builds and launches liquid-fuelled research rockets.",
  },
  {
    accent: "red",
    href: "https://reluntnu.no/",
    media: "dark",
    logo: "/assets/logos/relu.webp",
    logoAlt: "Relu",
    photo: "/assets/heroes/relu.webp",
    photoAlt: "Relu-presentasjon",
    category: "AI · Industri",
    categoryEn: "AI · Industry",
    name: "Relu",
    description: "Utvikler AI-løsninger i samarbeid med næringslivet.",
    descriptionEn: "Builds AI solutions in collaboration with industry.",
  },
  {
    accent: "teal",
    href: "https://www.revolve.no/",
    logo: "/assets/logos/revolve.webp",
    logoAlt: "Revolve NTNU",
    logoSize: "tall",
    photo: "/assets/heroes/revolve.webp",
    photoAlt: "Revolve-bil på banen",
    category: "Motorsport · Bil",
    categoryEn: "Motorsport · Cars",
    name: "Revolve NTNU",
    description:
      "Formula Student — designer og bygger en ny elektrisk racerbil hvert år.",
    descriptionEn:
      "Formula Student — designs and builds a new electric race car every year.",
  },
  {
    accent: "teal",
    href: "https://www.instagram.com/solanlinjeforening",
    logo: "/assets/logos/solan-new.webp",
    logoAlt: "Solan Linjeforening",
    logoSize: "tall",
    photo: "/assets/heroes/solan.webp",
    photoAlt: "Solan Linjeforening-teamet",
    category: "Linjeforening",
    categoryEn: "Student society",
    name: "Solan",
    description: "Linjeforeningen for Entreprenørskolen ved NTNU i Trondheim.",
    descriptionEn:
      "The student society for NTNU's School of Entrepreneurship in Trondheim.",
  },
  {
    accent: "blue",
    href: "https://sparkntnu.no/",
    logo: "/assets/spark-logo.webp",
    logoAlt: "Spark NTNU",
    photo: "/assets/heroes/spark-org.webp",
    photoAlt: "Spark NTNU-arrangement",
    photoPosition: "center top",
    category: "Veiledning",
    categoryEn: "Guidance",
    name: "Spark* NTNU",
    description:
      "Gratis veiledningstjeneste for studenter med en forretningsidé — mentorer, workshops og et program fra post-it til pilot.",
    descriptionEn:
      "A free guidance service for students with a business idea — mentors, workshops and a programme from post-it to pilot.",
  },
  {
    accent: "yellow",
    href: "https://www.startntnu.no/",
    logo: "/assets/partners/start-ntnu.webp",
    logoAlt: "Start NTNU",
    photo: "/assets/heroes/start.webp",
    photoAlt: "Start IT-arrangement",
    category: "Arrangør",
    categoryEn: "Events",
    name: "Start NTNU",
    description:
      "Norges største studentorganisasjon for entreprenørskap. Startup Weekend, pitch-kvelder og karriere­events.",
    descriptionEn:
      "Norway's largest student organisation for entrepreneurship. Startup Weekend, pitch nights and career events.",
  },
  {
    accent: "blue",
    href: "https://www.instagram.com/studiobeta/",
    logo: "/assets/logos/studiobeta.webp",
    logoAlt: "Studio Beta",
    photo: "/assets/heroes/studiobeta.webp",
    photoAlt: "Studio Beta-byggeprosjekt",
    category: "Arkitektur",
    categoryEn: "Architecture",
    name: "Studio Beta",
    description:
      "Studentdrevet arkitektur- og designstudio. Byggeprosjekter i full skala og prototyper.",
    descriptionEn:
      "A student-run architecture and design studio. Full-scale building projects and prototypes.",
  },
  {
    accent: "yellow",
    href: "https://www.stottehjulet.no/",
    logo: "/assets/logos/stottehjulet.webp",
    logoAlt: "Støttehjulet",
    logoSize: "big-tall",
    photo: "/assets/heroes/stottehjulet.avif",
    photoAlt: "Støttehjulet-teamet",
    category: "Konsulent · Organisasjon",
    categoryEn: "Consulting · Organisation",
    name: "Støttehjulet",
    description:
      "Hjelper organisasjoner med ledelse, samarbeid og organisasjonsutvikling.",
    descriptionEn:
      "Helps organisations with leadership, collaboration and organisational development.",
  },
  {
    accent: "red",
    href: "https://www.vortexntnu.no",
    media: "deeper",
    logo: "/assets/to/ascend.webp",
    logoAlt: "Vortex NTNU",
    logoSize: "big",
    photo: "/assets/heroes/vortex.webp",
    photoAlt: "Vortex ORCA undervannsfarkost",
    category: "Hav · Undervann",
    categoryEn: "Ocean · Underwater",
    name: "Vortex NTNU",
    description:
      "Bygger autonome undervannsfarkoster (ROV/AUV) til internasjonale konkurranser.",
    descriptionEn:
      "Builds autonomous underwater vehicles (ROV/AUV) for international competitions.",
  },
  {
    accent: "yellow",
    href: "https://www.instagram.com/wic_ntnu/",
    media: "dark",
    logo: "/assets/logos/wic.webp",
    logoAlt: "WIC — Women’s Investment Club",
    photo: "/assets/heroes/wic.webp",
    photoAlt: "WIC-arrangement",
    photoPosition: "center 35%",
    category: "Kvinnenettverk",
    categoryEn: "Women's network",
    name: "WIC",
    description:
      "Women’s Investment Club skaper møteplasser for kvinner med interesse for finans, investering og kapitalmarkeder.",
    descriptionEn:
      "The Women's Investment Club creates meetups for women interested in finance, investing and capital markets.",
  },
];
